swagger: "2.0"
info:
    title: The grand-game API
    description: This API serves the game
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /participants:
        get:
            tags:
                - game
            summary: participants game
            description: Returns all the participants and their information
            operationId: game#participants
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ParticipantResponse'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/GameParticipantsNotFoundResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/GameParticipantsInternalErrorResponseBody'
            schemes:
                - http
definitions:
    GameParticipantsInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: participants_internal_error_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    GameParticipantsNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: participants_not_found_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ParticipantResponse:
        title: ParticipantResponse
        type: object
        properties:
            Backstory:
                type: string
                description: Backstory of participant
                example: Non vel placeat atque ut.
            Email:
                type: string
                description: Email of participant
                example: Qui voluptatem iste sit quos accusamus.
            Favor:
                type: integer
                description: Influence of participant
                example: 1925194264753228056
                format: int64
            Gold:
                type: integer
                description: Gold of participant
                example: 6582447882786407178
                format: int64
            Id:
                type: integer
                description: Unique participant ID
                example: 8094623973123428774
                format: int64
            Kind:
                type: string
                description: Kind of participant
                example: admin
                enum:
                    - player
                    - admin
                    - superadmin
            Name:
                type: string
                description: Name of participant
                example: Qui veniam vel possimus quis ex est.
            Phone:
                type: string
                description: Phone number of participant
                example: Iusto perferendis ut quasi.
            Role:
                type: string
                description: Role of participant
                example: King's Hand
                enum:
                    - King
                    - King's Hand
                    - Archvizier
                    - Noble
                    - Mercenary
        example:
            Backstory: Minima consectetur officia.
            Email: Ipsum sequi temporibus harum id.
            Favor: 6988342502517981686
            Gold: 1419413462703561853
            Id: 2594621686688723007
            Kind: player
            Name: Rerum aut cupiditate ipsam aut.
            Phone: Velit voluptatum.
            Role: Mercenary
        required:
            - Id
            - Name
            - Email
            - Phone
            - Kind
            - Role
            - Backstory
            - Gold
            - Favor
